### PR TITLE
Add Twirp support

### PR DESCRIPTION
**Pull request by austinylin**
See kolide/launcher#245.

### CODE REVIEW

**Comment by patrickod** [comment]
Is there any update on this potentially shipping? AIUI this would be a significant usability improvement for people attempting to deploy on AWS.

**Comment by marpaia** [comment]
@patrickod I'd love to land this, but we need the PR to not pin to forks of Launcher and Go-Kit.

**Comment by marpaia** [comment]
From @groob to @austinylin in Slack on April 27, 2018 on the topic of landing this PR:

> Hey! Wanted to get your feedback. I was thinking of a few options. 
>
> 1) the go-kit PR has some feedback from the contributors. Idk what your thoughts/availability is to continue pushing it through code review. I’m pretty active in that space and wouldn’t mind opening a separate PR and driving it to a conclusion. But it’s your PR and I’d only want to do this if you’re too busy, uninterested or don’t care about getting the credit for the contribution :)
> 2) go-kit is just a bunch of libraries. To land support for twirp as a transport the go package itself doesn’t have to live within that namespace. we can keep your current but working prototype of the transport somewhere in a third party space. Then we can merge the transport options to fleet/launcher and refactor the transport further when the upstream changes are merged/final. This might also be a good option because we’d have some real feedback about usage to create consensus around the APIs. 
>
> Your PRs in launcher and fleet are good quality code and a lot of folks in the community have expressed interest in having these changes landed. So I’m happy to explore either of the above, or a third option.

**Comment by marpaia** [comment]
I'm closing this due to inactivity. @austinylin if you're able to circle back on this, we would love to re-open this PR and get this merged one of these days.

**Pull request closed without merging**
