### PR TITLE
Rename ignore-tls flag to tls-skip-verify

### PR DESCRIPTION
**Pull request by zwass**

### CODE REVIEW

**Comment by zwass** [comment]
My assertion is that `--insecure` will be much more intuitive to folks who are used to using that flag with `curl`.

**Comment by zwass** [comment]
I don't think it's the most accurate flag for what's going on. `--ignore-tls` gives the impression that TLS is not being used. What's really happening is that we are skipping certificate verification.

**Comment by marpaia** [comment]
I could see `--ignore-tls-cert` or `--tls-no-verify` then maybe?

**Comment by zwass** [comment]
I like `tls-no-verify` (or `tls-skip-verify`)

**Comment by zwass** [comment]
Updated to `tls-skip-verify`

**Pull request merged**
